import "./globals.css";
import Navbar from "./components/Navbar";
import WhatsAppWidget from "./components/WhatsappWidget";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <WhatsAppWidget />
      </body>
    </html>
  );
}
